version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: clinicia_db
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root_password
      - PORT=3001
    depends_on:
      - db

volumes:
  db_data:
